### ISSUE TITLE
import时有报错。感觉可能是util4sh.py的问题

### ISSUE THREAD

**Issue by Watanabe-Asa** [pcrbot/plugins-for-Hoshino#1]
[2020-08-04 14:23:41,224 nonebot] ERROR: Failed to import "hoshino.modules.shebot.setu", error: No module named 'filetype'
[2020-08-04 14:23:41,286 nonebot] ERROR: No module named 'filetype'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Hoshino3\HoshinoBot\hoshino\modules\shebot\setu\__init__.py", line 9, in <module>
    from .data_source import SetuWarehouse, save_config,load_config,send_setus
  File "C:\Hoshino3\HoshinoBot\hoshino\modules\shebot\setu\data_source.py", line 61, in <module>
    from hoshino.util4sh import Res as R
  File "C:\Hoshino3\HoshinoBot\hoshino\util4sh.py", line 9, in <module>
    import filetype
ModuleNotFoundError: No module named 'filetype'
[2020-08-04 14:23:41,443 nonebot] ERROR: Failed to import "hoshino.modules.shebot.var_replace", error: No module named 'filetype'
[2020-08-04 14:23:41,521 nonebot] ERROR: No module named 'filetype'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Hoshino3\HoshinoBot\hoshino\modules\shebot\var_replace.py", line 50, in <module>
    from hoshino.util4sh import get_random_file, Res as R
  File "C:\Hoshino3\HoshinoBot\hoshino\util4sh.py", line 9, in <module>
    import filetype
ModuleNotFoundError: No module named 'filetype'

**Comment by Watanabe-Asa** [comment]
解决方法 安装依赖
