### ISSUE TITLE
哔哩哔哩视频订阅报错

### ISSUE THREAD

**Issue by corvo007** [pcrbot/plugins-for-Hoshino#12]
订阅好up后检查更新时出现以下报错，提示json格式有误，而我去json校验网站发现json能校验通过，所以不知道是什么问题
```
[2020-09-05 20:00:20,221 B站投稿提醒] ERROR: Opening and ending tag mismatch: img line 35 and p, line 36, column 13 (<string>, line 36)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xcwbotDX\HoshinoBot\hoshino\service.py", line 324, in wrapper
    ret = await func()
  File "C:\Users\Administrator\Desktop\xcwbotDX\HoshinoBot\hoshino\modules\shebot\biliVideo\__init__.py", line 49, in check_BiliVideo
    video = BV.parse_xml()
  File "C:\Users\Administrator\Desktop\xcwbotDX\HoshinoBot\hoshino\modules\shebot\biliVideo\__init__.py", line 24, in parse_xml
    rss = etree.XML(self.xml)
  File "src\lxml\etree.pyx", line 3216, in lxml.etree.XML
  File "src\lxml\parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 36
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: img line 35 and p, line 36, column 13
```

**Comment by shewinder** [comment]
这个插件我自己也很久没用了，可以尝试使用infoPush替代

**Comment by corvo007** [comment]
#5 那 没 事 了
