### ISSUE TITLE
如果被rua的人头像就是GIF，合成会出错

### ISSUE THREAD

**Issue by Jerry-FaGe** [pcrbot/plugins-for-Hoshino#25]
[这个是出错的头像](http://q1.qlogo.cn/g?b=qq&nk=479773048&s=160)

应该是data_source还没有处理GIF的功能吧

错误日志
```
03-26 14:47:44 [ERROR] nonebot | Running matcher <Matcher from rua, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    nonebot.run(app="bot:app")
  File "/home/.local/lib/python3.8/site-packages/nonebot/__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/home/.local/lib/python3.8/site-packages/nonebot/message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
\> File "/home/.local/lib/python3.8/site-packages/nonebot/message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 527, in run
    await self.run_handler(handler, bot, event, state_)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 512, in run_handler
    await handler(
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 377, in wrapper
    await matcher.run_handler(func, bot, event, state)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 512, in run_handler
    await handler(
  File "src/plugins/rua/__init__.py", line 52, in handle_event
    #await rua.finish(MessageSegment.image(f'file:///data/output.gif'))
  File "src/plugins/rua/data_source.py", line 27, in generate_gif
    im.paste(avatar, avatar_pos[i], mask=avatar.split()[3])
IndexError: tuple index out of range
```

**Comment by shewinder** [comment]
是的，不支持gif。并且我也才知道头像可以是gif
